name: pdam_inventory
description: "PDAM Inventory"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  mobkit_dashed_border: ^0.0.6
  pie_chart: ^5.4.0
  internet_connection_checker: ^1.0.0+1
  dio: ^5.5.0+1
  shared_preferences: ^2.2.3
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/mulish/Mulish-Light.ttf
          weight: 300
        - asset: assets/fonts/mulish/Mulish-Regular.ttf
        - asset: assets/fonts/mulish/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/mulish/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/mulish/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/mulish/Mulish-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/mulish/Mulish-Black.ttf
          weight: 900
    - family: Prompt
      fonts:
        - asset: assets/fonts/prompt/Prompt-Light.ttf
          weight: 300
        - asset: assets/fonts/prompt/Prompt-Regular.ttf
        - asset: assets/fonts/prompt/Prompt-Medium.ttf
          weight: 500
        - asset: assets/fonts/prompt/Prompt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/prompt/Prompt-Bold.ttf
          weight: 700
        - asset: assets/fonts/prompt/Prompt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/prompt/Prompt-Black.ttf
          weight: 900
